set_languages("cxx17")
add_rules("mode.debug")

target("rv64_emulator")
    add_cxxflags("-g -std=c++17")
    add_defines("DEBUG")
    set_kind("binary")
    set_targetdir("build")
    add_includedirs(".")
    add_files("src/**.cc" )

target("gtest")
    set_languages("cxx11")
    set_kind("static")
    set_targetdir("build")
    add_includedirs("third_party/gtest")
    add_includedirs("third_party/gtest/include")
    add_files("third_party/gtest/src/gtest-all.cc")

target("gtest_main")
    set_languages("cxx11")
    set_kind("static")
    set_targetdir("build")
    add_includedirs("third_party/gtest")
    add_includedirs("third_party/gtest/include")
    add_files("third_party/gtest/src/gtest_main.cc")

target("gmock")
    set_languages("cxx11")
    set_kind("static")
    set_targetdir("build")
    add_deps("gtest_main")
    add_includedirs("third_party/gtest")
    add_includedirs("third_party/gtest/include")
    add_files("third_party/gtest/src/gmock-all.cc")

target("rv64_emulator_test")
    add_cxxflags("-fno-access-control -g -std=c++17")
    set_kind("binary")
    set_targetdir("build")
    add_includedirs(".")
    add_includedirs("third_party/gtest/include")
    add_files("test/**.cc")
    add_files("src/**.cc|rv64_emulator.cc")
    add_deps("gtest")
